.nh
.TH DVM1200 1
.SH SYNOPSIS
\fBdvm1200\fR [\fB-d <device>\fR] [\fB-c <count>\fR] [\fB-u\fR]

.SH DESCRIPTION
\fBdvm1200\fR is an open source tool to dump data from Velleman DVM
and convert it to CSV format.

.SH OPTIONS
\fB-d <device>\fR
  specify serial port to connect

.PP
\fB-c <count>\fR
  print \fBcount\fR measurements and exit

.PP
\fB-u\fR
  drop out duplicated measurement values

.SH BUGS
The DVM1200 send erroneous data when the battery is low

.SH AUTHOR
\fBdvm1200\fR was written by Luc Hondareyte - https://github.com/lhondareyte
