.\" Manpage for dvm1200.
.TH man 1 "14 April 2017" "1.0" "dvm1200 man page"
.SH NAME
dvm1200 \- Utility for Vellemann DVM1200 Digital Multimeter
.SH SYNOPSIS
dvm1200 [-d device] [-r] 
.SH DESCRIPTION
dvm1200 \- Utility for Vellemann DVM1200 (and clones) Digital Multimeters
dvm1200 dump data from dvm1200 and convert it to CSV format.
.SH OPTIONS

.SH BUGS
No known bugs.
.SH AUTHOR
Luc Hondareyte
