.\" Manpage for dvm1200.
.TH man 1 "14 May 2024" "1.1" "dvm1200 man page"
.SH NAME
dvm1200 \- Utility for Vellemann DVM1200 Digital Multimeter

.SH SYNOPSIS
.B dvm1200 
.RB [-d\ \fBdevice]
.RB [-c\ \fBcount] 
.RB [-u] 

.SH DESCRIPTION
.I dvm1200
is an open source tool to dump data from Velleman DVM and convert it to CSV format.

.SH OPTIONS
.TP
.BR \-d\ \fI<device>
specify serial port to connect
.TP
.BR \-c\ \fI<count>
Print count measurements and exit 
.TP
.BR \-u
Filter out repeated values in measurement

.SH BUGS
.TP
When battery is low, the DVM1200 send erratic data.

.SH AUTHOR
Luc Hondareyte
